// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"


const char THING_ID[] = "eee3f91e-......"; // adjust your Thing ID

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


int cO2_Concentration_ppm;
float pressure_bar;
CloudRelativeHumidity relative_humidity;
CloudTemperatureSensor temperature_combo_celsius;
CloudTemperatureSensor temperature_imu_celsius;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(temperature_imu_celsius, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(cO2_Concentration_ppm, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure_bar, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(relative_humidity, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature_combo_celsius, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
