:Author: Enrique Albertos
:Email:
:Date: 01/05/2021
:Revision: 1
:License: Public Domain

= Project: {Project}

This is an example for testing the VenTTracker Window Sensor
connecte to Arduino IoT Cloud.
Displays a progress bar indicating the window openes on 
a Monochrome OLED display based on SSD1306 drivers.
This example is for a 128x32 pixel display using I2C to communicate
3 pins are required to interface (two I2C and one reset).


Lights LED according sensor events:
                     | LEFT LED  |  RIGHT LED  |
WINDOW OPEN EVENT    |    OFF    |    OFF      |
WINDOW CLOSED EVENT  |    ON     |    ON       |
TO THE LEFT MOVEMENT |    ON     |    OFF      |
TO THE RIGHT MOVEMENT|    ON     |    OFF      |

  Arduino IoT Cloud Thing "VT-CR01-WW01"
https://create.arduino.cc/cloud/things/7c03b195-29d1-42ba-92e1-651a8e7d4010 




== Hardware. Pinout

8 A4/SDA Analog ADC in; I2C SDA; SDA to SDA OLED Display
9 A5/SCL Analog ADC in; I2C SCL to SCK OLED Display
13 RST Digital In Active low reset input  RESET to push button. Other end to ground.
14 GND Power Power Ground to Battery  - 
15 VIN Power In Vin Power input VIN to Baterry  + 
20 D2 Digital GPIO - to Open/Closed Reed Switches
25 D7 Digital; Right LED with a 100 Ohm resitor to ground
26 D8 Digital GPIO to Left LED with a 100 Ohm resitor to ground
27 D9/PWM Digital GPIO to  Right Reed Switch. Other end to ground.
28 D10/PWM Digital GPIO;  to Left Reed Switch. Other end to ground.


=== Cloud Variables

CloudSwitch windowOpen: (RO) indicates if the window is open or closed
CloudSwitch windowAlert; (RW) can signal the window in alert state
CloudPercentage windowPosition; (RO) indicates if the window open percentage (0%, 25%, 50%, 75%, 100%)
CloudLocation windowLocation; (RO) indicates window geolocation coordinates
CloudTemperature windowTemp; (RO) indicates window sensor IMU temperature.



